# Generated by Django 3.1.3 on 2020-11-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=120)),
            ],
        ),
    ]
